# Generated by Django 5.2.1 on 2025-06-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_complaint_failure_node_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='failure_node_description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='recovery_method_description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='service_company',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='client',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='engine_model_description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='front_axle_model_description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='model_description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='rear_axle_model_description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='service_company',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='service_company_description',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='transmission_model_description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type_description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='service_company',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='service_company_description',
        ),
        migrations.AddField(
            model_name='complaint',
            name='description_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions_complaint', to='service.reference'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='failure_node_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_node', to='service.reference'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recovery_method_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_method', to='service.reference'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_complaint', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='client_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_models', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='front_axle_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_axle_models', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='rear_axle_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rear_axle_models', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_machine', to='service.reference'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmission_models', to='service.reference'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='description_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions_maintenance', to='service.reference'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='service.reference'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='organization_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_maintenance', to='service.reference'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_maintenance', to='service.reference'),
        ),
    ]
